name: Simple GitHub Action

on:
  workflow_dispatch:   # IMPORTANT: manual trigger only

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 22f2000003@ds.study.iitm.ac.in
        run: echo "Hello, world!"
